### ISSUE TITLE
Why using the same encoder for encoding question, context and answer?

### ISSUE THREAD

**Issue by Gaozhen0816** [seanie12/Info-HCVAE#1]
https://github.com/seanie12/Info-HCVAE/blob/d7a8f08f36f6e15d5e3bf85d2cab70fd45e81192/vae/models.py#L201
![image](https://user-images.githubusercontent.com/7966596/88012223-f153ad00-cb4b-11ea-98fe-dd32f05b25b4.png)

**Comment by seanie12** [comment]
Sorry for the confusion. We performed two different experiments.
There might be some mixup when we factorize our codes.
I will check it and let you know as soon as possible.
Thanks

**Comment by seanie12** [comment]
We share all the parameters for question, context, and answer encoder in posterior networks.
