### ISSUE TITLE
Pre-trained models

### ISSUE THREAD

**Issue by jhyuklee** [seanie12/Info-HCVAE#5]
Hi, thank you for open sourcing your work. It's really nice. Do you have any plan to share the pre-trained QAG model that can reproduce the results in the paper (the one that you get from running `python main.py`)?

Otherwise, providing the generated QA pairs used in your work would be nice as well. Thanks.

(I missed the README saying it's TBA. I just want to know when they will be available)

**Comment by seanie12** [comment]
@jhyuklee 
Hi, we have updated our repository. We uploaded the generated QA pairs. You can download it from [here](https://drive.google.com/file/d/1CdhslOycNFDwnDo7e8c7GaxvYxHrUlFG/view?usp=sharing). 
More details are on the README. 
If you have any questions, feel free to contact us.

**Comment by jhyuklee** [comment]
Great! Thanks a lot.
