### ISSUE TITLE
How to generate multiple different questions/QA pairs from the same paragraph? (Table 6 and Table 7 in Experiments section)

### ISSUE THREAD

**Issue by zhanhl316** [seanie12/Info-HCVAE#8]
Dear authors,
     I just come across a small questions about the implementation of generating different question/QA pairs from the same paragraph. My question is:
     How to generate many different questions or QA pairs in Table 6 and Table 7 respectively,  when given the same paragraph? I mean, in your released code, it seems that I could not find the relevant part. If possible, could your please share the code about these part. I am just curious about how to generate different questions/QA pairs from the same paragraph, from a implementation perspective.
    Any feedback would be appriciated! Thanks

**Comment by seanie12** [comment]
Hi.

For a given paragraph, you sample multiple latent variables to decode several QA pairs.

In our implementation, it's super simple. you run translate.py  or generate_qa.py with argument k > 1.

**Comment by zhanhl316** [comment]
Thank you! I got your point!

Best,
Haolan

Seanie Lee <notifications@github.com> 于2021年2月5日周五 下午3:17写道：
